# Generated by Django 6.0 on 2025-12-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
