# Generated by Django 6.0 on 2025-12-25 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_job_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scraped_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.scrapedjob'),
        ),
    ]
