# Generated by Django 6.0 on 2026-01-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_job_scraped_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('interested', 'Interested'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('offer', 'Offer')], default='interested', max_length=20),
        ),
    ]
