# Generated by Django 6.0 on 2026-01-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedjob',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
